import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pouria Mahinsamadi Portfolio</title>
        <meta name="description" content="Generated by me" />
        <link rel="icon" href="/favion.ico" />
      </Head>
      <main></main>
    </div>
  );
}
