import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import Description from "./components/Description";
import Body from "./components/Body";
import Portfolio from "./components/Portfolio";
import { useState } from "react";


export default function Home() {
  const[darkMode, setDarkMode]= useState(false)
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className=" min-h-screen">
        <nav className="py-10 mb-12 flex justify-between dark:text-white">
      <h1 className="font-burtons text-xl">developedbyme</h1>
      <ul className="flex items-center">
        <li>
          <BsFillMoonStarsFill
            className=" cursor-pointer text-2xl"
            onClick={() => setDarkMode(!darkMode)}
          />
        </li>
        <li>
          <a
            href="#"
            className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
          >
            Resume
          </a>
        </li>
      </ul>
    </nav>
          <Description />
        </section>
        <Body/>
        <Portfolio/>
      </main>
    </div>
  );
}
